[
{"Month":"2017-07","Property type":"House","Location":"Auckland","Measure":"Median sale price","Value":"915000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-07","Property type":"House","Location":"Christchurch","Measure":"Median sale price","Value":"445000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-07","Property type":"House","Location":"North Island Metro","Measure":"Median sale price","Value":"538000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-07","Property type":"House","Location":"Other","Measure":"Median sale price","Value":"385000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-07","Property type":"House","Location":"South Island Metro","Measure":"Median sale price","Value":"335000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-07","Property type":"House","Location":"Wellington","Measure":"Median sale price","Value":"583000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-07","Property type":"Apartment","Location":"Auckland","Measure":"Median sale price","Value":"620000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-07","Property type":"Apartment","Location":"Christchurch","Measure":"Median sale price","Value":"342000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-07","Property type":"Apartment","Location":"North Island Metro","Measure":"Median sale price","Value":"390000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-07","Property type":"Apartment","Location":"Other","Measure":"Median sale price","Value":"287250","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-07","Property type":"Apartment","Location":"South Island Metro","Measure":"Median sale price","Value":"269000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-07","Property type":"Apartment","Location":"Wellington","Measure":"Median sale price","Value":"400000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-08","Property type":"House","Location":"Auckland","Measure":"Median sale price","Value":"912500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-08","Property type":"House","Location":"Christchurch","Measure":"Median sale price","Value":"437000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-08","Property type":"House","Location":"North Island Metro","Measure":"Median sale price","Value":"548750","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-08","Property type":"House","Location":"Other","Measure":"Median sale price","Value":"383250","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-08","Property type":"House","Location":"South Island Metro","Measure":"Median sale price","Value":"333500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-08","Property type":"House","Location":"Wellington","Measure":"Median sale price","Value":"590000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-08","Property type":"Apartment","Location":"Auckland","Measure":"Median sale price","Value":"640000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-08","Property type":"Apartment","Location":"Christchurch","Measure":"Median sale price","Value":"345000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-08","Property type":"Apartment","Location":"North Island Metro","Measure":"Median sale price","Value":"385000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-08","Property type":"Apartment","Location":"Other","Measure":"Median sale price","Value":"285000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-08","Property type":"Apartment","Location":"South Island Metro","Measure":"Median sale price","Value":"277500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-08","Property type":"Apartment","Location":"Wellington","Measure":"Median sale price","Value":"430000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-09","Property type":"House","Location":"Auckland","Measure":"Median sale price","Value":"918000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-09","Property type":"House","Location":"Christchurch","Measure":"Median sale price","Value":"458250","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-09","Property type":"House","Location":"North Island Metro","Measure":"Median sale price","Value":"546500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-09","Property type":"House","Location":"Other","Measure":"Median sale price","Value":"397334.5","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-09","Property type":"House","Location":"South Island Metro","Measure":"Median sale price","Value":"347250","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-09","Property type":"House","Location":"Wellington","Measure":"Median sale price","Value":"595000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-09","Property type":"Apartment","Location":"Auckland","Measure":"Median sale price","Value":"625000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-09","Property type":"Apartment","Location":"Christchurch","Measure":"Median sale price","Value":"348000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-09","Property type":"Apartment","Location":"North Island Metro","Measure":"Median sale price","Value":"419000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-09","Property type":"Apartment","Location":"Other","Measure":"Median sale price","Value":"304000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-09","Property type":"Apartment","Location":"South Island Metro","Measure":"Median sale price","Value":"276500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-09","Property type":"Apartment","Location":"Wellington","Measure":"Median sale price","Value":"400000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-10","Property type":"House","Location":"Auckland","Measure":"Median sale price","Value":"928500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-10","Property type":"House","Location":"Christchurch","Measure":"Median sale price","Value":"481781","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-10","Property type":"House","Location":"North Island Metro","Measure":"Median sale price","Value":"545000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-10","Property type":"House","Location":"Other","Measure":"Median sale price","Value":"397825","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-10","Property type":"House","Location":"South Island Metro","Measure":"Median sale price","Value":"369500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-10","Property type":"House","Location":"Wellington","Measure":"Median sale price","Value":"615000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-10","Property type":"Apartment","Location":"Auckland","Measure":"Median sale price","Value":"655000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-10","Property type":"Apartment","Location":"Christchurch","Measure":"Median sale price","Value":"343000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-10","Property type":"Apartment","Location":"North Island Metro","Measure":"Median sale price","Value":"423750","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-10","Property type":"Apartment","Location":"Other","Measure":"Median sale price","Value":"310500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-10","Property type":"Apartment","Location":"South Island Metro","Measure":"Median sale price","Value":"252500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-10","Property type":"Apartment","Location":"Wellington","Measure":"Median sale price","Value":"430000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-11","Property type":"House","Location":"Auckland","Measure":"Median sale price","Value":"981800","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-11","Property type":"House","Location":"Christchurch","Measure":"Median sale price","Value":"477500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-11","Property type":"House","Location":"North Island Metro","Measure":"Median sale price","Value":"553000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-11","Property type":"House","Location":"Other","Measure":"Median sale price","Value":"398000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-11","Property type":"House","Location":"South Island Metro","Measure":"Median sale price","Value":"355637.5","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-11","Property type":"House","Location":"Wellington","Measure":"Median sale price","Value":"656500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-11","Property type":"Apartment","Location":"Auckland","Measure":"Median sale price","Value":"645000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-11","Property type":"Apartment","Location":"Christchurch","Measure":"Median sale price","Value":"302000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-11","Property type":"Apartment","Location":"North Island Metro","Measure":"Median sale price","Value":"400000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-11","Property type":"Apartment","Location":"Other","Measure":"Median sale price","Value":"295000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-11","Property type":"Apartment","Location":"South Island Metro","Measure":"Median sale price","Value":"280575","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-11","Property type":"Apartment","Location":"Wellington","Measure":"Median sale price","Value":"423500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-12","Property type":"House","Location":"Auckland","Measure":"Median sale price","Value":"925000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-12","Property type":"House","Location":"Christchurch","Measure":"Median sale price","Value":"465000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-12","Property type":"House","Location":"North Island Metro","Measure":"Median sale price","Value":"560000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-12","Property type":"House","Location":"Other","Measure":"Median sale price","Value":"405000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-12","Property type":"House","Location":"South Island Metro","Measure":"Median sale price","Value":"360000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-12","Property type":"House","Location":"Wellington","Measure":"Median sale price","Value":"620000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-12","Property type":"Apartment","Location":"Auckland","Measure":"Median sale price","Value":"607000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-12","Property type":"Apartment","Location":"Christchurch","Measure":"Median sale price","Value":"345000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-12","Property type":"Apartment","Location":"North Island Metro","Measure":"Median sale price","Value":"425000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-12","Property type":"Apartment","Location":"Other","Measure":"Median sale price","Value":"290000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-12","Property type":"Apartment","Location":"South Island Metro","Measure":"Median sale price","Value":"300000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2017-12","Property type":"Apartment","Location":"Wellington","Measure":"Median sale price","Value":"440000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-01","Property type":"House","Location":"Auckland","Measure":"Median sale price","Value":"880000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-01","Property type":"House","Location":"Christchurch","Measure":"Median sale price","Value":"450000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-01","Property type":"House","Location":"North Island Metro","Measure":"Median sale price","Value":"520000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-01","Property type":"House","Location":"Other","Measure":"Median sale price","Value":"400000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-01","Property type":"House","Location":"South Island Metro","Measure":"Median sale price","Value":"365000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-01","Property type":"House","Location":"Wellington","Measure":"Median sale price","Value":"550000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-01","Property type":"Apartment","Location":"Auckland","Measure":"Median sale price","Value":"600000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-01","Property type":"Apartment","Location":"Christchurch","Measure":"Median sale price","Value":"345000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-01","Property type":"Apartment","Location":"North Island Metro","Measure":"Median sale price","Value":"390000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-01","Property type":"Apartment","Location":"Other","Measure":"Median sale price","Value":"310500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-01","Property type":"Apartment","Location":"South Island Metro","Measure":"Median sale price","Value":"264000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-01","Property type":"Apartment","Location":"Wellington","Measure":"Median sale price","Value":"397000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-02","Property type":"House","Location":"Auckland","Measure":"Median sale price","Value":"915500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-02","Property type":"House","Location":"Christchurch","Measure":"Median sale price","Value":"470500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-02","Property type":"House","Location":"North Island Metro","Measure":"Median sale price","Value":"550000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-02","Property type":"House","Location":"Other","Measure":"Median sale price","Value":"405000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-02","Property type":"House","Location":"South Island Metro","Measure":"Median sale price","Value":"358750","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-02","Property type":"House","Location":"Wellington","Measure":"Median sale price","Value":"655794","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-02","Property type":"Apartment","Location":"Auckland","Measure":"Median sale price","Value":"670000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-02","Property type":"Apartment","Location":"Christchurch","Measure":"Median sale price","Value":"359500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-02","Property type":"Apartment","Location":"North Island Metro","Measure":"Median sale price","Value":"414000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-02","Property type":"Apartment","Location":"Other","Measure":"Median sale price","Value":"300000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-02","Property type":"Apartment","Location":"South Island Metro","Measure":"Median sale price","Value":"222500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-02","Property type":"Apartment","Location":"Wellington","Measure":"Median sale price","Value":"432000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-03","Property type":"House","Location":"Auckland","Measure":"Median sale price","Value":"950000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-03","Property type":"House","Location":"Christchurch","Measure":"Median sale price","Value":"480000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-03","Property type":"House","Location":"North Island Metro","Measure":"Median sale price","Value":"570000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-03","Property type":"House","Location":"Other","Measure":"Median sale price","Value":"400000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-03","Property type":"House","Location":"South Island Metro","Measure":"Median sale price","Value":"390000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-03","Property type":"House","Location":"Wellington","Measure":"Median sale price","Value":"665000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-03","Property type":"Apartment","Location":"Auckland","Measure":"Median sale price","Value":"631500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-03","Property type":"Apartment","Location":"Christchurch","Measure":"Median sale price","Value":"357500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-03","Property type":"Apartment","Location":"North Island Metro","Measure":"Median sale price","Value":"423000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-03","Property type":"Apartment","Location":"Other","Measure":"Median sale price","Value":"311507","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-03","Property type":"Apartment","Location":"South Island Metro","Measure":"Median sale price","Value":"287500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-03","Property type":"Apartment","Location":"Wellington","Measure":"Median sale price","Value":"441000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-04","Property type":"House","Location":"Auckland","Measure":"Median sale price","Value":"898000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-04","Property type":"House","Location":"Christchurch","Measure":"Median sale price","Value":"462300","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-04","Property type":"House","Location":"North Island Metro","Measure":"Median sale price","Value":"554000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-04","Property type":"House","Location":"Other","Measure":"Median sale price","Value":"408000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-04","Property type":"House","Location":"South Island Metro","Measure":"Median sale price","Value":"380000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-04","Property type":"House","Location":"Wellington","Measure":"Median sale price","Value":"636750","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-04","Property type":"Apartment","Location":"Auckland","Measure":"Median sale price","Value":"617500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-04","Property type":"Apartment","Location":"Christchurch","Measure":"Median sale price","Value":"366780.5","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-04","Property type":"Apartment","Location":"North Island Metro","Measure":"Median sale price","Value":"419500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-04","Property type":"Apartment","Location":"Other","Measure":"Median sale price","Value":"304000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-04","Property type":"Apartment","Location":"South Island Metro","Measure":"Median sale price","Value":"332000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-04","Property type":"Apartment","Location":"Wellington","Measure":"Median sale price","Value":"385500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-05","Property type":"House","Location":"Auckland","Measure":"Median sale price","Value":"925000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-05","Property type":"House","Location":"Christchurch","Measure":"Median sale price","Value":"457500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-05","Property type":"House","Location":"North Island Metro","Measure":"Median sale price","Value":"560000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-05","Property type":"House","Location":"Other","Measure":"Median sale price","Value":"399874.5","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-05","Property type":"House","Location":"South Island Metro","Measure":"Median sale price","Value":"360000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-05","Property type":"House","Location":"Wellington","Measure":"Median sale price","Value":"615000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-05","Property type":"Apartment","Location":"Auckland","Measure":"Median sale price","Value":"615000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-05","Property type":"Apartment","Location":"Christchurch","Measure":"Median sale price","Value":"347500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-05","Property type":"Apartment","Location":"North Island Metro","Measure":"Median sale price","Value":"391000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-05","Property type":"Apartment","Location":"Other","Measure":"Median sale price","Value":"306750","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-05","Property type":"Apartment","Location":"South Island Metro","Measure":"Median sale price","Value":"295800","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-05","Property type":"Apartment","Location":"Wellington","Measure":"Median sale price","Value":"452750","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-06","Property type":"House","Location":"Auckland","Measure":"Median sale price","Value":"909750","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-06","Property type":"House","Location":"Christchurch","Measure":"Median sale price","Value":"450000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-06","Property type":"House","Location":"North Island Metro","Measure":"Median sale price","Value":"575000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-06","Property type":"House","Location":"Other","Measure":"Median sale price","Value":"393000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-06","Property type":"House","Location":"South Island Metro","Measure":"Median sale price","Value":"400100","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-06","Property type":"House","Location":"Wellington","Measure":"Median sale price","Value":"647500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-06","Property type":"Apartment","Location":"Auckland","Measure":"Median sale price","Value":"655000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-06","Property type":"Apartment","Location":"Christchurch","Measure":"Median sale price","Value":"343000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-06","Property type":"Apartment","Location":"North Island Metro","Measure":"Median sale price","Value":"429000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-06","Property type":"Apartment","Location":"Other","Measure":"Median sale price","Value":"288188.5","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-06","Property type":"Apartment","Location":"South Island Metro","Measure":"Median sale price","Value":"230000","Value Unit":"nzd","Value Label":"NZD","Null Reason":""},
{"Month":"2018-06","Property type":"Apartment","Location":"Wellington","Measure":"Median sale price","Value":"406500","Value Unit":"nzd","Value Label":"NZD","Null Reason":""}
]
